### PR TITLE
Firefox support, graduate students support, "all score" board support

### PR DESCRIPTION
**Pull request by bigeagle**
RT~

### CODE REVIEW

**Comment by summivox** [comment]
Pull & rebase please.
Thanks for the tip! I'm in a rush for release so didn't bother to test on Firefox.

**Comment by summivox** [comment]
BTW, do you think we should filter `***`?

**Comment by bigeagle** [comment]
clicking and dragging cursor finding the score is `***` is more fun~

**Comment by summivox** [comment]
good, rebase on my head then

**Comment by bigeagle** [comment]
rebased~

**Comment by summivox** [comment]
thx and will look at it later~

**Comment by summivox** [comment]
I'm at this page: http://zhjw.cic.tsinghua.edu.cn/cj.cjCjbAll.do?m=bks_cjdcx&cjdlx=zw&flag=di1

CSS Selector not working. Perhaps your HTML structure is different from mine.
Can you post your HTML on gist (`yjs_cjdcx`)?

**Comment by summivox** [comment]
I think I have `#table1 tr:not(:first-child) > td:nth-child(4)`.

**Comment by bigeagle** [comment]
my html source: http://paste.kde.org/792998/
the table doesn't have an `id` attribute

**Pull request merged**
